### ISSUE TITLE
Configurable "GITLAB_URL" from Environment Variable

### ISSUE THREAD

**Issue by mukeshkmr776** [NodeSecure/gitlab#84]
Currrently variable **GITLAB_URL** is fixed string. 
It should be configurable so that users can also use it to download repositories from local GitLab(on-premise) also.

Something like below can be done:
`GITLAB_URL = process.env.GITLAB_URL || 'https://gitlab.com/api/v4/projects/'`

Or, user can only provide the hostname and then complete URL can be formed internally with **BASE_API_URL=/api/v4/projects/** 

And then some validations on URL can be performed.

**Comment by fraxken** [comment]
Hey @mukeshkmr776

Good idea. I completely forgot at the time to manage this. I will check my planning to commit this soon.

**Comment by fraxken** [comment]
Feature implemented in the new migrated version `@nodesecure/gitlab`.
